"""Initial migration.

Revision ID: 545a8c548340
Revises: abf688340be3
Create Date: 2025-01-26 21:27:51.355868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545a8c548340'
down_revision = 'abf688340be3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('scheduled_time',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('scheduled_time',
               existing_type=sa.String(length=5),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
